/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'vouldjeff' at '3/18/16 2:15 PM' with Gradle 2.11
 *
 * @author vouldjeff, @date 3/18/16 2:15 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
